---
- name: "Deploy to production"
  hosts: production
  tasks:
    - pip:
        name:
          - jsondiff
          - pyyaml
    - name: Push Docker Compose file
      copy:
        src: ./docker-compose.yml
        dest: "{{ compose_file }}"
    - name: Create temp folder
      file:
        path: "{{ tmp_folder }}"
        state: directory
        mode: '0755'
    # Required so the image is ready when we want to run scala code
    - name: Pull latest scala server runtime
      docker_image:
        name: docker.pkg.github.com/lambdacademy-dev/scala-runner/scala-runner-runtime:0.3.4
        source: pull
    - name: Deploy stack
      docker_stack:
        name: lambdacademy
        prune: yes
        with_registry_auth: yes
        resolve_image: always
        compose:
          - "{{ compose_file }}"