---
- name: "Configure Server"
  hosts: production
  roles:
    - ./roles/commons
    - ./roles/docker-swarm
    - ./roles/docker-github-package
- name: "Deploy Production"
  hosts: production
  tasks:
    - pip:
        name:
          - jsondiff
          - pyyaml
    - name: Push Docker Compose file
      copy:
        src: ./production-compose.yml
        dest: "{{ compose_file }}"
    - name: Deploy stack
      docker_stack:
        name: lambdacademy
        prune: yes
        with_registry_auth: yes
        resolve_image: always
        compose:
          - "{{ compose_file }}"