name: CD

on:
  push:
    tags:
      - deploy-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible
    - name: Install Roles
      run: ansible-galaxy role install -r roles/requirements.yml
    - name: Decrypt SSH Key
      env:
        VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
      run: |
        echo $VAULT_PASSWORD > password
        ansible-vault decrypt secrets/production --vault-password-file password
        rm password
    - name: Add known hosts
      run: sudo ssh-keyscan -H 94.237.88.82 >> ~/.ssh/known_hosts
    - name: Execute Ansible Playbook
      run: ansible-playbook  -i inventory.yml production-playbook.yml
    - name: Clean
      run: rm -rf secrets
